### PR TITLE
Updating java dependencies

### PR DESCRIPTION
**Pull request by DarkSorrow**
I'm trying to install the module with node V8.9 and its not compiling on older version of the java dependencies.
After upgrading it it was working

### CODE REVIEW

**Review by zuazo — CHANGES_REQUESTED** [review]
Thanks for the PR! :smile: And sorry for the delay in my review.

Could you update the link to the java library in the README to point to the new version?

**Comment by DarkSorrow** [comment]
Added the new link in the readme, it was only this right?

**Review by zuazo — APPROVED** [review]
Yes, that one. Sorry for not being more specific.

Thank you! :+1:

**Comment by zuazo** [comment]
Released in version [`0.7.0`](https://github.com/zuazo/node-jmx/releases/tag/0.7.0).

**Pull request merged**
